# Generated by Django 4.0.1 on 2022-01-08 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_alter_transacao_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='descricao',
            new_name='objeto',
        ),
    ]
