# Generated by Django 4.0.1 on 2022-01-08 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_rename_descricao_transacao_objeto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='objeto',
            new_name='nome',
        ),
    ]
